ДЗ1
Dayz221/IT-dep-hw pull request #1
Opened 2024-10-22 16:44 UTC by Dayz221

2024-10-22 16:59 UTC, Impervguin requested changes

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	buf := make([]byte, 64)
Константу лучше вынести в отдельную константную переменную

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	var text string
Подход рабочий, но ты никак блоки не обрабатываешь в дальнейшем по отдельности, поэтому почему бы просто не os.ReadFile?)

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +		if err == io.EOF {
А если другая ошибка?

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +			break
Использование break - плохой тон, когда можно записать условие в заголовке цикла. Иногда без него не обойтись, но как правило можно. Без него код стане более читаемым

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	myText := ReadFile("input.txt")
Пусть имя входного файла подаётся либо как аргумент командной строки, либо по приглашению ко вводу

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	myMap := make(map[string]int, 10)
Лучше задать размер как параметр от количества полученных на вход строк. Предугадать как много может потребоваться сложно, но можно взять например (количество строк / 10 при количестве > 1000 и 100 иначе)

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +		myMap[line] += 1
++

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +		if cnt == 1 && len(line) != 0 {
Вместо того, чтобы в каждый раз в цикле проверять, что длина строки не равна 0, лучше вне цикла сделать map['']=0

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	uniqTextLines := []string{}
В случае если уникальных строк много, то массив будет много раз перевыделятся. Вероятно эффективнее будет сначала посчитать число уникальных строк, выделить массив, и уже заполнить его

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +	uniqTextLines := []string{}
Создание массивов лучше делать через make

2024-10-22 16:59 UTC, Impervguin commented on main.go
> +		file.WriteString("Не нашель уникальных строк...")
Так как по заданию не просили отдельной обработки случая без уникальных строк, то лучше выходной файл оставить пустым

2024-10-22 16:59 UTC, Impervguin commented on output.txt
> +ПОЧЕМУ У НАС - 22 байт
Вопрос на +: почему символов 12,  байт -- 22?

2024-10-22 17:15 UTC, Impervguin commented
Из репы также убери код, выходные/входные данные к проекту не отностся

2024-10-22 17:15 UTC, Impervguin commented
В readme.md описать формат входных/выходных данных и там дать краткий пример

2024-10-22 17:24 UTC, Dayz221 commented on output.txt
> +ПОЧЕМУ У НАС - 22 байт
потому что русские символы занимают 2 байта, а пробелы 1

2024-10-22 17:25 UTC, Impervguin requested changes

2024-10-22 17:25 UTC, Impervguin commented on main.go
> +		fmt.Println("Не смог открыть файл...")
Выводить в функции сообщение об ошибке не надо. Нужно саму ошибку обернуть через fmt.Errorf, и передаить выше

2024-10-22 17:25 UTC, Impervguin commented on main.go
> +	myText := ReadFile("input.txt")
Вот тут надо ошибку обработать

2024-10-22 17:25 UTC, Impervguin commented on main.go
> +		os.Exit(1)
В данном случае не критично, но про os.Exit(1) не сработают defer, поэтому лучше return

2024-10-22 17:25 UTC, Impervguin commented on main.go
> +		fmt.Println("Не смог создать файл...")
никак не выводишь информацию об ошибке

2024-10-22 17:25 UTC, Impervguin commented
вообще программу стоит разделить на три функции
readFile возвращает слайс строк
proccessText возвращает слайс уникальных строк
writeFile пишет уникальные строки в файлы

мейн выглядит так:
read
if err
process
if err
write
if err

2024-10-22 17:25 UTC, Impervguin commented
то есть мейн просто принимает входные данные, вызывает функции, выводит ошибки

2024-10-22 17:52 UTC, Dayz221 commented on main.go
> +		myMap[line] += 1
питон...

2024-10-23 11:01 UTC, Impervguin requested changes

2024-10-23 11:01 UTC, Impervguin commented on main.go
> +	text = strings.ReplaceAll(text, "\r", "")
Не относится к функции чтения файла, это уже обработка

2024-10-23 11:01 UTC, Impervguin commented on main.go
> +			file.WriteString(strings.ToUpper(line) + " - " + strconv.Itoa(len(line)) + " байт \n")
Лучше использовать fmt.Sprintf, и её результат подавать на запись

2024-10-23 11:01 UTC, Impervguin commented on main.go
> +			file.WriteString(strings.ToUpper(line) + " - " + strconv.Itoa(len(line)) + " байт \n")
Насколько я помню len возвращает количество символом, а не размер в байтах. Проверь, могу быть не прав

2024-10-23 11:01 UTC, Impervguin commented on main.go
> +	myText, err := ReadFile(os.Args[1])
А где проверка, что аргументы вообще пришли?

2024-10-23 11:01 UTC, Impervguin commented on main.go
> +			file.WriteString(strings.ToUpper(line) + " - " + strconv.Itoa(len(line)) + " байт \n")
Перевод в верхний регистр это не про вывод, а про обработку

2024-10-23 11:04 UTC, Dayz221 commented on main.go
> +			file.WriteString(strings.ToUpper(line) + " - " + strconv.Itoa(len(line)) + " байт \n")
не, это размер, в выводе же размер в байтах

2024-10-23 11:44 UTC, Dayz221 commented on main.go
> +			file.WriteString(strings.ToUpper(line) + " - " + strconv.Itoa(len(line)) + " байт \n")
https://pkg.go.dev/builtin#len

2024-10-23 14:36 UTC, Impervguin commented
Одобрено, молодец

2024-10-23 15:28 UTC, merged